/* Copyright (C) Dominic R and contributors (see AUTHORS)
 *
 * Licensed under GNU General Public License v2
 *   (see COPYING for full license text)
 */

#define USE_THE_REPOSITORY_VARIABLE

#include "cgit.h"
#include "ui-shared.h"
#include "cmd.h"
#include "html.h"
#include "version.h"
#include "ui-shared-links.h"
#include "ui-shared-forms.h"

static const char cgit_doctype[] =
"<!DOCTYPE html>\n";

static void print_rel_vcs_link(const char *url)
{
	html("<link rel='vcs-git' href='");
	html_attr(url);
	html("' title='");
	html_attr(ctx.repo->name);
	html(" Git repository'/>\n");
}

static void base64url_encode(const char *src, int len, struct strbuf *dst)
{
	static const char t[] =
		"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
	int i;

	for (i = 0; i < len; i += 3) {
		unsigned a = (unsigned char)src[i];
		unsigned b = (i + 1 < len) ? (unsigned char)src[i + 1] : 0;
		unsigned c = (i + 2 < len) ? (unsigned char)src[i + 2] : 0;
		strbuf_addch(dst, t[a >> 2]);
		strbuf_addch(dst, t[((a & 3) << 4) | (b >> 4)]);
		if (i + 1 < len)
			strbuf_addch(dst, t[((b & 0xf) << 2) | (c >> 6)]);
		if (i + 2 < len)
			strbuf_addch(dst, t[c & 0x3f]);
	}
}

static const char *asset_cache_key(void)
{
	static struct strbuf key = STRBUF_INIT;

	if (key.len)
		return key.buf;

	{
		struct strbuf json = STRBUF_INIT;
		strbuf_addf(&json,
			    "{\"v\":\"%s\",\"d\":\"%s\",\"t\":\"%s\"}",
			    cgit_version, __DATE__, __TIME__);
		base64url_encode(json.buf, json.len, &key);
		strbuf_release(&json);
	}
	return key.buf;
}

static int emit_css_link(struct string_list_item *s, void *arg)
{
	/* Do not emit anything if css= is specified. */
	if (s && *s->string == '\0')
		return 0;

	html("<link rel='stylesheet' type='text/css' href='");
	if (s)
		html_attr(s->string);
	else
		html_attr((const char *)arg);
	htmlf("?__cb=%s", asset_cache_key());
	html("'/>\n");

	return 0;
}

static int emit_js_link(struct string_list_item *s, void *arg)
{
	/* Do not emit anything if js= is specified. */
	if (s && *s->string == '\0')
		return 0;

	html("<script type='text/javascript' src='");
	if (s)
		html_attr(s->string);
	else
		html_attr((const char *)arg);
	htmlf("?__cb=%s", asset_cache_key());
	html("'></script>\n");

	return 0;
}

void cgit_print_docstart(void)
{
	char *host = cgit_hosturl();

	if (ctx.cfg.embedded) {
		if (ctx.cfg.header)
			html_include(ctx.cfg.header);
		return;
	}

	html(cgit_doctype);
	html("<html lang='en'>\n");
	html("<head>\n");
	html("<title>");
	html_txt(ctx.page.title);
	html("</title>\n");
	htmlf("<meta name='generator' content='cgit %s'/>\n", cgit_version);
	html("<meta name='viewport' content='width=device-width, initial-scale=1'/>\n");
	if (ctx.cfg.robots && *ctx.cfg.robots)
		htmlf("<meta name='robots' content='%s'/>\n", ctx.cfg.robots);

	if (ctx.cfg.css.items)
		for_each_string_list(&ctx.cfg.css, emit_css_link, NULL);
	else
		emit_css_link(NULL, "/cgit.css");

	if (ctx.cfg.js.items)
		for_each_string_list(&ctx.cfg.js, emit_js_link, NULL);
	else
		emit_js_link(NULL, "/cgit.js");

	if (ctx.cfg.favicon) {
		html("<link rel='shortcut icon' href='");
		html_attr(ctx.cfg.favicon);
		html("'/>\n");
	}
	if (host && ctx.repo && ctx.qry.head) {
		char *fileurl;
		struct strbuf sb = STRBUF_INIT;
		strbuf_addf(&sb, "h=%s", ctx.qry.head);

		html("<link rel='alternate' title='Atom feed' href='");
		html(cgit_httpscheme());
		html_attr(host);
		fileurl = cgit_fileurl(ctx.repo->url, "atom", ctx.qry.vpath,
				       sb.buf);
		html_attr(fileurl);
		html("' type='application/atom+xml'/>\n");
		strbuf_release(&sb);
		free(fileurl);
	}
	if (ctx.repo)
		cgit_add_clone_urls(print_rel_vcs_link);
	if (ctx.cfg.head_include)
		html_include(ctx.cfg.head_include);
	if (ctx.repo && ctx.repo->extra_head_content)
		html(ctx.repo->extra_head_content);
	html("</head>\n");
	html("<body>\n");
	if (ctx.cfg.header)
		html_include(ctx.cfg.header);
	free(host);
}

void cgit_print_docend(void)
{
	html("</div> <!-- class=content -->\n");
	if (ctx.cfg.embedded) {
		html("</div> <!-- id=cgit -->\n");
		if (ctx.cfg.footer)
			html_include(ctx.cfg.footer);
		return;
	}
	if (ctx.cfg.footer)
		html_include(ctx.cfg.footer);
	else {
		htmlf("<div class='footer'>generated by <a href='https://github.com/dominic-r/gitweb'>cgit %s</a> "
			"(<a href='https://git-scm.com/'>git %s</a>) at ", cgit_version, git_version_string);
		html_txt(show_date(time(NULL), 0, cgit_date_mode(DATE_ISO8601)));
		html(" · <a href='#' id='theme-toggle' onclick='cycleTheme(); return false;'>auto</a>");
		html("</div>\n");
	}
	html("</div> <!-- id=cgit -->\n");
	html("</body>\n</html>\n");
}

void cgit_print_error_page(int code, const char *msg, const char *fmt, ...)
{
	va_list ap;
	ctx.page.expires = ctx.cfg.cache_dynamic_ttl;
	ctx.page.status = code;
	ctx.page.statusmsg = msg;
	cgit_print_layout_start();
	va_start(ap, fmt);
	cgit_vprint_error(fmt, ap);
	va_end(ap);
	cgit_print_layout_end();
}

void cgit_print_layout_start(void)
{
	cgit_print_http_headers();
	cgit_print_docstart();
	cgit_print_pageheader();
}

void cgit_print_layout_end(void)
{
	cgit_print_docend();
}


static const char *hc(const char *page)
{
	if (!ctx.qry.page)
		return NULL;

	return strcmp(ctx.qry.page, page) ? NULL : "active";
}

static void cgit_print_path_crumbs(char *path)
{
	char *old_path = ctx.qry.path;
	char *p = path, *q, *end = path + strlen(path);
	int levels = 0;

	ctx.qry.path = NULL;
	cgit_self_link("root", NULL, NULL);
	ctx.qry.path = p = path;
	while (p < end) {
		if (!(q = strchr(p, '/')) || levels > 15)
			q = end;
		*q = '\0';
		html_txt("/");
		cgit_self_link(p, NULL, NULL);
		if (q < end)
			*q = '/';
		p = q + 1;
		++levels;
	}
	ctx.qry.path = old_path;
}

static void print_header(void)
{
	char *logo = NULL, *logo_link = NULL;

	html("<table id='header'>\n");
	html("<tr>\n");

	if (ctx.repo && ctx.repo->logo && *ctx.repo->logo)
		logo = ctx.repo->logo;
	else
		logo = ctx.cfg.logo;
	if (ctx.repo && ctx.repo->logo_link && *ctx.repo->logo_link)
		logo_link = ctx.repo->logo_link;
	else
		logo_link = ctx.cfg.logo_link;
	if (logo && *logo) {
		html("<td class='logo' rowspan='2'><a href='");
		if (logo_link && *logo_link)
			html_attr(logo_link);
		else
			html_attr(cgit_rooturl());
		html("'><img src='");
		html_attr(logo);
		html("' alt='cgit logo'/></a></td>\n");
	}

	html("<td class='main'>");
	if (ctx.repo) {
		cgit_index_link("index", NULL, NULL, NULL, NULL, 0, 1);
		html(" : ");
		cgit_summary_link(ctx.repo->name, NULL, NULL, NULL);
		if (ctx.env.authenticated) {
			html("</td><td class='form'>");
			html("<form method='get'>\n");
			cgit_add_hidden_formfields(0, 1, ctx.qry.page);
			html("<select name='h' onchange='this.form.submit();'>\n");
			refs_for_each_branch_ref(get_main_ref_store(the_repository),
						 cgit_print_branch_option, ctx.qry.head);
			if (ctx.repo->enable_remote_branches)
				refs_for_each_remote_ref(get_main_ref_store(the_repository),
							 cgit_print_branch_option, ctx.qry.head);
			html("</select> ");
			html("<input type='submit' value='switch'/>");
			html("</form>");
		}
	} else
		html_txt(ctx.cfg.root_title);
	html("</td></tr>\n");

	html("<tr><td class='sub'>");
	if (ctx.repo) {
		html_txt(ctx.repo->desc);
		html("</td><td class='sub right'>");
		if (ctx.repo->owner_filter) {
			cgit_open_filter(ctx.repo->owner_filter);
			html_txt(ctx.repo->owner);
			cgit_close_filter(ctx.repo->owner_filter);
		} else {
			html_txt(ctx.repo->owner);
		}
	} else {
		if (ctx.cfg.root_desc)
			html_txt(ctx.cfg.root_desc);
	}
	html("</td></tr></table>\n");
}

void cgit_print_pageheader(void)
{
	html("<div id='cgit'>");
	if (!ctx.env.authenticated || !ctx.cfg.noheader)
		print_header();

	html("<table class='tabs'><tr><td>\n");
	if (ctx.env.authenticated && ctx.repo) {
		if (ctx.repo->readme.nr)
			cgit_reporevlink("about", "about", NULL,
				    hc("about"), ctx.qry.head, NULL,
				    NULL);
		cgit_summary_link("summary", NULL, hc("summary"),
				  ctx.qry.head);
		cgit_refs_link("refs", NULL, hc("refs"), ctx.qry.head,
			       ctx.qry.oid, NULL);
		cgit_log_link("log", NULL, hc("log"), ctx.qry.head,
			      NULL, ctx.qry.vpath, 0, NULL, NULL,
			      ctx.qry.showmsg, ctx.qry.follow);
		if (ctx.qry.page && !strcmp(ctx.qry.page, "blame"))
			cgit_blame_link("blame", NULL, hc("blame"), ctx.qry.head,
				        ctx.qry.oid, ctx.qry.vpath);
		else
			cgit_tree_link("tree", NULL, hc("tree"), ctx.qry.head,
				       ctx.qry.oid, ctx.qry.vpath);
		cgit_commit_link("commit", NULL, hc("commit"),
				 ctx.qry.head, ctx.qry.oid, ctx.qry.vpath);
		cgit_diff_link("diff", NULL, hc("diff"), ctx.qry.head,
			       ctx.qry.oid, ctx.qry.oid2, ctx.qry.vpath);
		cgit_search_link("search", NULL, hc("search"),
				 ctx.qry.head, NULL);
		if (ctx.repo->max_stats)
			cgit_stats_link("stats", NULL, hc("stats"),
					ctx.qry.head, ctx.qry.vpath);
		cgit_compare_link("compare", NULL, hc("compare"),
				  ctx.qry.head, NULL, NULL);
		if (ctx.repo->homepage) {
			html("<a href='");
			html_attr(ctx.repo->homepage);
			html("'>homepage</a>");
		}
		html("</td><td class='form'>");
		html("<form class='right' method='get' action='");
		if (ctx.cfg.virtual_root) {
			const char *form_page = (ctx.qry.page && !strcmp(ctx.qry.page, "search")) ? "search" : "log";
			char *fileurl = cgit_fileurl(ctx.qry.repo, form_page,
						   ctx.qry.vpath, NULL);
			html_url_path(fileurl);
			free(fileurl);
		}
		html("'>\n");
		if (ctx.qry.page && !strcmp(ctx.qry.page, "search")) {
			cgit_add_hidden_formfields(1, 0, "search");
			html("<select name='qt'>\n");
			html_option("file", "file name", ctx.qry.grep);
			html_option("code", "code", ctx.qry.grep);
			html("</select>\n");
		} else {
			cgit_add_hidden_formfields(1, 0, "log");
			html("<select name='qt'>\n");
			html_option("grep", "log msg", ctx.qry.grep);
			html_option("author", "author", ctx.qry.grep);
			html_option("committer", "committer", ctx.qry.grep);
			html_option("range", "range", ctx.qry.grep);
			html("</select>\n");
		}
		html("<input class='txt' type='search' size='10' name='q' value='");
		html_attr(ctx.qry.search);
		html("'/>\n");
		html("<input type='submit' value='search'/>\n");
		html("</form>\n");
	} else if (ctx.env.authenticated) {
		char *currenturl = cgit_currenturl();
		cgit_site_link(NULL, "index", NULL, hc("repolist"), NULL, NULL, 0, 1);
		if (ctx.cfg.root_readme)
			cgit_site_link("about", "about", NULL, hc("about"),
				  NULL, NULL, 0, 1);
		html("</td><td class='form'>");
		html("<form method='get' action='");
		html_attr(currenturl);
		html("'>\n");
		html("<input type='search' name='q' size='10' value='");
		html_attr(ctx.qry.search);
		html("'/>\n");
		html("<input type='submit' value='search'/>\n");
		html("</form>");
		free(currenturl);
	}
	html("</td></tr></table>\n");
	if (ctx.env.authenticated && ctx.repo && ctx.qry.vpath) {
		html("<div class='path'>");
		html("path: ");
		cgit_print_path_crumbs(ctx.qry.vpath);
		if (ctx.cfg.enable_follow_links && !strcmp(ctx.qry.page, "log")) {
			html(" (");
			ctx.qry.follow = !ctx.qry.follow;
			cgit_self_link(ctx.qry.follow ? "follow" : "unfollow",
					NULL, NULL);
			ctx.qry.follow = !ctx.qry.follow;
			html(")");
		}
		html("</div>");
	}
	if (ctx.env.authenticated && ctx.repo && ctx.qry.head &&
	    ctx.repo->defbranch && strcmp(ctx.qry.head, ctx.repo->defbranch)) {
		char *compare_url;
		struct strbuf query = STRBUF_INIT;

		strbuf_addf(&query, "id=%s&id2=%s",
			    ctx.repo->defbranch, ctx.qry.head);
		compare_url = cgit_pageurl(ctx.repo->url, "compare",
					   query.buf);
		html("<div class='compare-banner'>");
		html("Viewing branch <strong>");
		html_txt(ctx.qry.head);
		html("</strong> · <a href='");
		html_attr(compare_url);
		html("'>Compare with ");
		html_txt(ctx.repo->defbranch);
		html("</a>");
		html("</div>");
		strbuf_release(&query);
		free(compare_url);
	}
	html("<div class='content'>");
}
